server:
  #set port number to 0 to have the port number automatically set to random port which
  #is useful when multiple instances of the service are launched
  port: 0

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8010/eureka

spring:
  application:
    name: user-ms
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/photoapp?useSSL=false&serverTimezone=UTC
    username: kwd-admin
    password: ${MYSQL_PASS}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
        format_sql: true
        generate_statistics:
gateway:
  ip: 192.168.1.48
token:
  expiration_delay: 3600000 #one hour
  secret: Zuu-^@?eEpx@pg8j%Dj3W6rAEZm@44=JgcWJE$3pn_eUjA2s
